//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SisTictecks.Web.GestionCitasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionCitasWS.IGestionCitasService")]
    public interface IGestionCitasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCitasService/ListarCitas", ReplyAction="http://tempuri.org/IGestionCitasService/ListarCitasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IGestionCitasService/ListarCitasRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.EL.CitaEN> ListarCitas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCitasService/ListarCitas", ReplyAction="http://tempuri.org/IGestionCitasService/ListarCitasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.CitaEN>> ListarCitasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionCitasServiceChannel : UPC.SisTictecks.Web.GestionCitasWS.IGestionCitasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionCitasServiceClient : System.ServiceModel.ClientBase<UPC.SisTictecks.Web.GestionCitasWS.IGestionCitasService>, UPC.SisTictecks.Web.GestionCitasWS.IGestionCitasService {
        
        public GestionCitasServiceClient() {
        }
        
        public GestionCitasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionCitasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCitasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCitasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.EL.CitaEN> ListarCitas() {
            return base.Channel.ListarCitas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.CitaEN>> ListarCitasAsync() {
            return base.Channel.ListarCitasAsync();
        }
    }
}
