//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SisTictecks.TestWS.TalleresWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TalleresWS.ITallerService")]
    public interface ITallerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallerService/ListarTalleres", ReplyAction="http://tempuri.org/ITallerService/ListarTalleresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/ITallerService/ListarTalleresRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.EL.TallerEN> ListarTalleres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallerService/ListarTalleres", ReplyAction="http://tempuri.org/ITallerService/ListarTalleresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.TallerEN>> ListarTalleresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallerService/ObtenerTaller", ReplyAction="http://tempuri.org/ITallerService/ObtenerTallerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/ITallerService/ObtenerTallerRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.TallerEN ObtenerTaller(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallerService/ObtenerTaller", ReplyAction="http://tempuri.org/ITallerService/ObtenerTallerResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.TallerEN> ObtenerTallerAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITallerServiceChannel : UPC.SisTictecks.TestWS.TalleresWS.ITallerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TallerServiceClient : System.ServiceModel.ClientBase<UPC.SisTictecks.TestWS.TalleresWS.ITallerService>, UPC.SisTictecks.TestWS.TalleresWS.ITallerService {
        
        public TallerServiceClient() {
        }
        
        public TallerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TallerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TallerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TallerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.EL.TallerEN> ListarTalleres() {
            return base.Channel.ListarTalleres();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.TallerEN>> ListarTalleresAsync() {
            return base.Channel.ListarTalleresAsync();
        }
        
        public UPC.SisTictecks.EL.TallerEN ObtenerTaller(int codigo) {
            return base.Channel.ObtenerTaller(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.TallerEN> ObtenerTallerAsync(int codigo) {
            return base.Channel.ObtenerTallerAsync(codigo);
        }
    }
}
