//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SisTictecks.TestWS.ServiciosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosWS.IServicios")]
    public interface IServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearServicio", ReplyAction="http://tempuri.org/IServicios/CrearServicioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IServicios/CrearServicioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.ServicioEN CrearServicio(string descripcion, decimal valor, bool estado, int tiempoEstimadoHH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearServicio", ReplyAction="http://tempuri.org/IServicios/CrearServicioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> CrearServicioAsync(string descripcion, decimal valor, bool estado, int tiempoEstimadoHH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ObtenerServicio", ReplyAction="http://tempuri.org/IServicios/ObtenerServicioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IServicios/ObtenerServicioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.ServicioEN ObtenerServicio(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ObtenerServicio", ReplyAction="http://tempuri.org/IServicios/ObtenerServicioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> ObtenerServicioAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ModificarServicio", ReplyAction="http://tempuri.org/IServicios/ModificarServicioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IServicios/ModificarServicioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.ServicioEN ModificarServicio(int codigo, string descripcion, decimal valor, bool estado, int tiempoEstimadoHH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ModificarServicio", ReplyAction="http://tempuri.org/IServicios/ModificarServicioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> ModificarServicioAsync(int codigo, string descripcion, decimal valor, bool estado, int tiempoEstimadoHH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarServicio", ReplyAction="http://tempuri.org/IServicios/EliminarServicioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IServicios/EliminarServicioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        void EliminarServicio(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarServicio", ReplyAction="http://tempuri.org/IServicios/EliminarServicioResponse")]
        System.Threading.Tasks.Task EliminarServicioAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ListarServicios", ReplyAction="http://tempuri.org/IServicios/ListarServiciosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IServicios/ListarServiciosRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN> ListarServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ListarServicios", ReplyAction="http://tempuri.org/IServicios/ListarServiciosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN>> ListarServiciosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosChannel : UPC.SisTictecks.TestWS.ServiciosWS.IServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<UPC.SisTictecks.TestWS.ServiciosWS.IServicios>, UPC.SisTictecks.TestWS.ServiciosWS.IServicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPC.SisTictecks.EL.ServicioEN CrearServicio(string descripcion, decimal valor, bool estado, int tiempoEstimadoHH) {
            return base.Channel.CrearServicio(descripcion, valor, estado, tiempoEstimadoHH);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> CrearServicioAsync(string descripcion, decimal valor, bool estado, int tiempoEstimadoHH) {
            return base.Channel.CrearServicioAsync(descripcion, valor, estado, tiempoEstimadoHH);
        }
        
        public UPC.SisTictecks.EL.ServicioEN ObtenerServicio(int codigo) {
            return base.Channel.ObtenerServicio(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> ObtenerServicioAsync(int codigo) {
            return base.Channel.ObtenerServicioAsync(codigo);
        }
        
        public UPC.SisTictecks.EL.ServicioEN ModificarServicio(int codigo, string descripcion, decimal valor, bool estado, int tiempoEstimadoHH) {
            return base.Channel.ModificarServicio(codigo, descripcion, valor, estado, tiempoEstimadoHH);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> ModificarServicioAsync(int codigo, string descripcion, decimal valor, bool estado, int tiempoEstimadoHH) {
            return base.Channel.ModificarServicioAsync(codigo, descripcion, valor, estado, tiempoEstimadoHH);
        }
        
        public void EliminarServicio(int codigo) {
            base.Channel.EliminarServicio(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarServicioAsync(int codigo) {
            return base.Channel.EliminarServicioAsync(codigo);
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN> ListarServicios() {
            return base.Channel.ListarServicios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN>> ListarServiciosAsync() {
            return base.Channel.ListarServiciosAsync();
        }
    }
}
