//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SisTictecks.TestWS.ServiciosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosWS.IServicioService")]
    public interface IServicioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioService/ListarServicios", ReplyAction="http://tempuri.org/IServicioService/ListarServiciosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IServicioService/ListarServiciosRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN> ListarServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioService/ListarServicios", ReplyAction="http://tempuri.org/IServicioService/ListarServiciosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN>> ListarServiciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioService/ObtenerServicio", ReplyAction="http://tempuri.org/IServicioService/ObtenerServicioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IServicioService/ObtenerServicioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.ServicioEN ObtenerServicio(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioService/ObtenerServicio", ReplyAction="http://tempuri.org/IServicioService/ObtenerServicioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> ObtenerServicioAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioServiceChannel : UPC.SisTictecks.TestWS.ServiciosWS.IServicioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioServiceClient : System.ServiceModel.ClientBase<UPC.SisTictecks.TestWS.ServiciosWS.IServicioService>, UPC.SisTictecks.TestWS.ServiciosWS.IServicioService {
        
        public ServicioServiceClient() {
        }
        
        public ServicioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN> ListarServicios() {
            return base.Channel.ListarServicios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN>> ListarServiciosAsync() {
            return base.Channel.ListarServiciosAsync();
        }
        
        public UPC.SisTictecks.EL.ServicioEN ObtenerServicio(int codigo) {
            return base.Channel.ObtenerServicio(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> ObtenerServicioAsync(int codigo) {
            return base.Channel.ObtenerServicioAsync(codigo);
        }
    }
}
