//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SisTictecks.Web.VehiculoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoEN", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
    [System.SerializableAttribute()]
    public partial class VehiculoEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.SisTictecks.Web.VehiculoWS.ColorEN ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KilometrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.SisTictecks.Web.VehiculoWS.MarcaEN MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.SisTictecks.Web.VehiculoWS.ModeloEN ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((this.AnioField.Equals(value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.SisTictecks.Web.VehiculoWS.ColorEN Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kilometros {
            get {
                return this.KilometrosField;
            }
            set {
                if ((this.KilometrosField.Equals(value) != true)) {
                    this.KilometrosField = value;
                    this.RaisePropertyChanged("Kilometros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.SisTictecks.Web.VehiculoWS.MarcaEN Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.SisTictecks.Web.VehiculoWS.ModeloEN Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorEN", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
    [System.SerializableAttribute()]
    public partial class ColorEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarcaEN", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
    [System.SerializableAttribute()]
    public partial class MarcaEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloEN", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
    [System.SerializableAttribute()]
    public partial class ModeloEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.SisTictecks.Web.VehiculoWS.MarcaEN MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.SisTictecks.Web.VehiculoWS.MarcaEN Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VehiculoWS.IVehiculoService")]
    public interface IVehiculoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/CrearVehiculo", ReplyAction="http://tempuri.org/IVehiculoService/CrearVehiculoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/CrearVehiculoRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.Web.VehiculoWS.VehiculoEN CrearVehiculo(UPC.SisTictecks.Web.VehiculoWS.VehiculoEN vehiculoCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/CrearVehiculo", ReplyAction="http://tempuri.org/IVehiculoService/CrearVehiculoResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN> CrearVehiculoAsync(UPC.SisTictecks.Web.VehiculoWS.VehiculoEN vehiculoCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ObtenerVehiculo", ReplyAction="http://tempuri.org/IVehiculoService/ObtenerVehiculoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ObtenerVehiculoRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.Web.VehiculoWS.VehiculoEN ObtenerVehiculo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ObtenerVehiculo", ReplyAction="http://tempuri.org/IVehiculoService/ObtenerVehiculoResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN> ObtenerVehiculoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ModificarVehiculo", ReplyAction="http://tempuri.org/IVehiculoService/ModificarVehiculoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ModificarVehiculoRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.Web.VehiculoWS.VehiculoEN ModificarVehiculo(UPC.SisTictecks.Web.VehiculoWS.VehiculoEN vehiculoModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ModificarVehiculo", ReplyAction="http://tempuri.org/IVehiculoService/ModificarVehiculoResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN> ModificarVehiculoAsync(UPC.SisTictecks.Web.VehiculoWS.VehiculoEN vehiculoModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/EliminarVehiculo", ReplyAction="http://tempuri.org/IVehiculoService/EliminarVehiculoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/EliminarVehiculoRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        bool EliminarVehiculo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/EliminarVehiculo", ReplyAction="http://tempuri.org/IVehiculoService/EliminarVehiculoResponse")]
        System.Threading.Tasks.Task<bool> EliminarVehiculoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ListarVehiculos", ReplyAction="http://tempuri.org/IVehiculoService/ListarVehiculosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ListarVehiculosRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN> ListarVehiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ListarVehiculos", ReplyAction="http://tempuri.org/IVehiculoService/ListarVehiculosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN>> ListarVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ListarMarcas", ReplyAction="http://tempuri.org/IVehiculoService/ListarMarcasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ListarMarcasRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.MarcaEN> ListarMarcas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ListarMarcas", ReplyAction="http://tempuri.org/IVehiculoService/ListarMarcasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.MarcaEN>> ListarMarcasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ObtenerMarca", ReplyAction="http://tempuri.org/IVehiculoService/ObtenerMarcaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ObtenerMarcaRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.Web.VehiculoWS.MarcaEN ObtenerMarca(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ObtenerMarca", ReplyAction="http://tempuri.org/IVehiculoService/ObtenerMarcaResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.MarcaEN> ObtenerMarcaAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ListarModelos", ReplyAction="http://tempuri.org/IVehiculoService/ListarModelosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ListarModelosRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.ModeloEN> ListarModelos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ListarModelos", ReplyAction="http://tempuri.org/IVehiculoService/ListarModelosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.ModeloEN>> ListarModelosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ObtenerModelo", ReplyAction="http://tempuri.org/IVehiculoService/ObtenerModeloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ObtenerModeloRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.Web.VehiculoWS.ModeloEN ObtenerModelo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ObtenerModelo", ReplyAction="http://tempuri.org/IVehiculoService/ObtenerModeloResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.ModeloEN> ObtenerModeloAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ListarColores", ReplyAction="http://tempuri.org/IVehiculoService/ListarColoresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ListarColoresRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.ColorEN> ListarColores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ListarColores", ReplyAction="http://tempuri.org/IVehiculoService/ListarColoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.ColorEN>> ListarColoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ObtenerColor", ReplyAction="http://tempuri.org/IVehiculoService/ObtenerColorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.Web.VehiculoWS.RepetidoException), Action="http://tempuri.org/IVehiculoService/ObtenerColorRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.Web.VehiculoWS.ColorEN ObtenerColor(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculoService/ObtenerColor", ReplyAction="http://tempuri.org/IVehiculoService/ObtenerColorResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.ColorEN> ObtenerColorAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehiculoServiceChannel : UPC.SisTictecks.Web.VehiculoWS.IVehiculoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculoServiceClient : System.ServiceModel.ClientBase<UPC.SisTictecks.Web.VehiculoWS.IVehiculoService>, UPC.SisTictecks.Web.VehiculoWS.IVehiculoService {
        
        public VehiculoServiceClient() {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPC.SisTictecks.Web.VehiculoWS.VehiculoEN CrearVehiculo(UPC.SisTictecks.Web.VehiculoWS.VehiculoEN vehiculoCrear) {
            return base.Channel.CrearVehiculo(vehiculoCrear);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN> CrearVehiculoAsync(UPC.SisTictecks.Web.VehiculoWS.VehiculoEN vehiculoCrear) {
            return base.Channel.CrearVehiculoAsync(vehiculoCrear);
        }
        
        public UPC.SisTictecks.Web.VehiculoWS.VehiculoEN ObtenerVehiculo(int codigo) {
            return base.Channel.ObtenerVehiculo(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN> ObtenerVehiculoAsync(int codigo) {
            return base.Channel.ObtenerVehiculoAsync(codigo);
        }
        
        public UPC.SisTictecks.Web.VehiculoWS.VehiculoEN ModificarVehiculo(UPC.SisTictecks.Web.VehiculoWS.VehiculoEN vehiculoModificar) {
            return base.Channel.ModificarVehiculo(vehiculoModificar);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN> ModificarVehiculoAsync(UPC.SisTictecks.Web.VehiculoWS.VehiculoEN vehiculoModificar) {
            return base.Channel.ModificarVehiculoAsync(vehiculoModificar);
        }
        
        public bool EliminarVehiculo(int codigo) {
            return base.Channel.EliminarVehiculo(codigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarVehiculoAsync(int codigo) {
            return base.Channel.EliminarVehiculoAsync(codigo);
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN> ListarVehiculos() {
            return base.Channel.ListarVehiculos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.VehiculoEN>> ListarVehiculosAsync() {
            return base.Channel.ListarVehiculosAsync();
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.MarcaEN> ListarMarcas() {
            return base.Channel.ListarMarcas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.MarcaEN>> ListarMarcasAsync() {
            return base.Channel.ListarMarcasAsync();
        }
        
        public UPC.SisTictecks.Web.VehiculoWS.MarcaEN ObtenerMarca(int codigo) {
            return base.Channel.ObtenerMarca(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.MarcaEN> ObtenerMarcaAsync(int codigo) {
            return base.Channel.ObtenerMarcaAsync(codigo);
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.ModeloEN> ListarModelos() {
            return base.Channel.ListarModelos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.ModeloEN>> ListarModelosAsync() {
            return base.Channel.ListarModelosAsync();
        }
        
        public UPC.SisTictecks.Web.VehiculoWS.ModeloEN ObtenerModelo(int codigo) {
            return base.Channel.ObtenerModelo(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.ModeloEN> ObtenerModeloAsync(int codigo) {
            return base.Channel.ObtenerModeloAsync(codigo);
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.ColorEN> ListarColores() {
            return base.Channel.ListarColores();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.Web.VehiculoWS.ColorEN>> ListarColoresAsync() {
            return base.Channel.ListarColoresAsync();
        }
        
        public UPC.SisTictecks.Web.VehiculoWS.ColorEN ObtenerColor(int codigo) {
            return base.Channel.ObtenerColor(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.Web.VehiculoWS.ColorEN> ObtenerColorAsync(int codigo) {
            return base.Channel.ObtenerColorAsync(codigo);
        }
    }
}
