//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SisTictecks.TestWS.ParametrosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParametrosWS.IParametrosService")]
    public interface IParametrosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/ListarServicios", ReplyAction="http://tempuri.org/IParametrosService/ListarServiciosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IParametrosService/ListarServiciosRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN> ListarServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/ListarServicios", ReplyAction="http://tempuri.org/IParametrosService/ListarServiciosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN>> ListarServiciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/ObtenerServicio", ReplyAction="http://tempuri.org/IParametrosService/ObtenerServicioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IParametrosService/ObtenerServicioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.ServicioEN ObtenerServicio(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/ObtenerServicio", ReplyAction="http://tempuri.org/IParametrosService/ObtenerServicioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> ObtenerServicioAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/ListarTalleres", ReplyAction="http://tempuri.org/IParametrosService/ListarTalleresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IParametrosService/ListarTalleresRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.EL.TallerEN> ListarTalleres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/ListarTalleres", ReplyAction="http://tempuri.org/IParametrosService/ListarTalleresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.TallerEN>> ListarTalleresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/ObtenerTaller", ReplyAction="http://tempuri.org/IParametrosService/ObtenerTallerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IParametrosService/ObtenerTallerRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.TallerEN ObtenerTaller(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/ObtenerTaller", ReplyAction="http://tempuri.org/IParametrosService/ObtenerTallerResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.TallerEN> ObtenerTallerAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParametrosServiceChannel : UPC.SisTictecks.TestWS.ParametrosWS.IParametrosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParametrosServiceClient : System.ServiceModel.ClientBase<UPC.SisTictecks.TestWS.ParametrosWS.IParametrosService>, UPC.SisTictecks.TestWS.ParametrosWS.IParametrosService {
        
        public ParametrosServiceClient() {
        }
        
        public ParametrosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParametrosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametrosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametrosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN> ListarServicios() {
            return base.Channel.ListarServicios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.ServicioEN>> ListarServiciosAsync() {
            return base.Channel.ListarServiciosAsync();
        }
        
        public UPC.SisTictecks.EL.ServicioEN ObtenerServicio(int codigo) {
            return base.Channel.ObtenerServicio(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.ServicioEN> ObtenerServicioAsync(int codigo) {
            return base.Channel.ObtenerServicioAsync(codigo);
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.EL.TallerEN> ListarTalleres() {
            return base.Channel.ListarTalleres();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.TallerEN>> ListarTalleresAsync() {
            return base.Channel.ListarTalleresAsync();
        }
        
        public UPC.SisTictecks.EL.TallerEN ObtenerTaller(int codigo) {
            return base.Channel.ObtenerTaller(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.TallerEN> ObtenerTallerAsync(int codigo) {
            return base.Channel.ObtenerTallerAsync(codigo);
        }
    }
}
