//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SisTictecks.TestWS.GestionUsuariosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionUsuariosWS.IUsuariosService")]
    public interface IUsuariosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/CrearUsuario", ReplyAction="http://tempuri.org/IUsuariosService/CrearUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IUsuariosService/CrearUsuarioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.UsuarioEN CrearUsuario(UPC.SisTictecks.EL.UsuarioEN usuarioCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/CrearUsuario", ReplyAction="http://tempuri.org/IUsuariosService/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.UsuarioEN> CrearUsuarioAsync(UPC.SisTictecks.EL.UsuarioEN usuarioCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IUsuariosService/ObtenerUsuarioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.UsuarioEN ObtenerUsuario(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.UsuarioEN> ObtenerUsuarioAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/ModificarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IUsuariosService/ModificarUsuarioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.UsuarioEN ModificarUsuario(UPC.SisTictecks.EL.UsuarioEN usuarioModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.UsuarioEN> ModificarUsuarioAsync(UPC.SisTictecks.EL.UsuarioEN usuarioModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/EliminarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IUsuariosService/EliminarUsuarioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        bool EliminarUsuario(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/ListarUsuariosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/IUsuariosService/ListarUsuariosRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        System.Collections.Generic.List<UPC.SisTictecks.EL.UsuarioEN> ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.UsuarioEN>> ListarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ValidarNombreDeUsuarioExistente", ReplyAction="http://tempuri.org/IUsuariosService/ValidarNombreDeUsuarioExistenteResponse")]
        bool ValidarNombreDeUsuarioExistente(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ValidarNombreDeUsuarioExistente", ReplyAction="http://tempuri.org/IUsuariosService/ValidarNombreDeUsuarioExistenteResponse")]
        System.Threading.Tasks.Task<bool> ValidarNombreDeUsuarioExistenteAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ValidarCorreoExistente", ReplyAction="http://tempuri.org/IUsuariosService/ValidarCorreoExistenteResponse")]
        bool ValidarCorreoExistente(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ValidarCorreoExistente", ReplyAction="http://tempuri.org/IUsuariosService/ValidarCorreoExistenteResponse")]
        System.Threading.Tasks.Task<bool> ValidarCorreoExistenteAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerPerfil", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerPerfilResponse")]
        UPC.SisTictecks.EL.PerfilEN ObtenerPerfil(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerPerfil", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerPerfilResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.PerfilEN> ObtenerPerfilAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ListarPerfiles", ReplyAction="http://tempuri.org/IUsuariosService/ListarPerfilesResponse")]
        System.Collections.Generic.List<UPC.SisTictecks.EL.PerfilEN> ListarPerfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ListarPerfiles", ReplyAction="http://tempuri.org/IUsuariosService/ListarPerfilesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.PerfilEN>> ListarPerfilesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosServiceChannel : UPC.SisTictecks.TestWS.GestionUsuariosWS.IUsuariosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosServiceClient : System.ServiceModel.ClientBase<UPC.SisTictecks.TestWS.GestionUsuariosWS.IUsuariosService>, UPC.SisTictecks.TestWS.GestionUsuariosWS.IUsuariosService {
        
        public UsuariosServiceClient() {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPC.SisTictecks.EL.UsuarioEN CrearUsuario(UPC.SisTictecks.EL.UsuarioEN usuarioCrear) {
            return base.Channel.CrearUsuario(usuarioCrear);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.UsuarioEN> CrearUsuarioAsync(UPC.SisTictecks.EL.UsuarioEN usuarioCrear) {
            return base.Channel.CrearUsuarioAsync(usuarioCrear);
        }
        
        public UPC.SisTictecks.EL.UsuarioEN ObtenerUsuario(int codigo) {
            return base.Channel.ObtenerUsuario(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.UsuarioEN> ObtenerUsuarioAsync(int codigo) {
            return base.Channel.ObtenerUsuarioAsync(codigo);
        }
        
        public UPC.SisTictecks.EL.UsuarioEN ModificarUsuario(UPC.SisTictecks.EL.UsuarioEN usuarioModificar) {
            return base.Channel.ModificarUsuario(usuarioModificar);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.UsuarioEN> ModificarUsuarioAsync(UPC.SisTictecks.EL.UsuarioEN usuarioModificar) {
            return base.Channel.ModificarUsuarioAsync(usuarioModificar);
        }
        
        public bool EliminarUsuario(int codigo) {
            return base.Channel.EliminarUsuario(codigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int codigo) {
            return base.Channel.EliminarUsuarioAsync(codigo);
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.EL.UsuarioEN> ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.UsuarioEN>> ListarUsuariosAsync() {
            return base.Channel.ListarUsuariosAsync();
        }
        
        public bool ValidarNombreDeUsuarioExistente(string usuario) {
            return base.Channel.ValidarNombreDeUsuarioExistente(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarNombreDeUsuarioExistenteAsync(string usuario) {
            return base.Channel.ValidarNombreDeUsuarioExistenteAsync(usuario);
        }
        
        public bool ValidarCorreoExistente(string correo) {
            return base.Channel.ValidarCorreoExistente(correo);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCorreoExistenteAsync(string correo) {
            return base.Channel.ValidarCorreoExistenteAsync(correo);
        }
        
        public UPC.SisTictecks.EL.PerfilEN ObtenerPerfil(int codigo) {
            return base.Channel.ObtenerPerfil(codigo);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.PerfilEN> ObtenerPerfilAsync(int codigo) {
            return base.Channel.ObtenerPerfilAsync(codigo);
        }
        
        public System.Collections.Generic.List<UPC.SisTictecks.EL.PerfilEN> ListarPerfiles() {
            return base.Channel.ListarPerfiles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UPC.SisTictecks.EL.PerfilEN>> ListarPerfilesAsync() {
            return base.Channel.ListarPerfilesAsync();
        }
    }
}
