//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SisTictecks.Web.SeguridadWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeguridadWS.ISeguridadService")]
    public interface ISeguridadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridadService/AutenticarUsuario", ReplyAction="http://tempuri.org/ISeguridadService/AutenticarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UPC.SisTictecks.EL.RepetidoException), Action="http://tempuri.org/ISeguridadService/AutenticarUsuarioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UPC.SisTictecks.EL")]
        UPC.SisTictecks.EL.UsuarioEN AutenticarUsuario(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridadService/AutenticarUsuario", ReplyAction="http://tempuri.org/ISeguridadService/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<UPC.SisTictecks.EL.UsuarioEN> AutenticarUsuarioAsync(string usuario, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISeguridadServiceChannel : UPC.SisTictecks.Web.SeguridadWS.ISeguridadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadServiceClient : System.ServiceModel.ClientBase<UPC.SisTictecks.Web.SeguridadWS.ISeguridadService>, UPC.SisTictecks.Web.SeguridadWS.ISeguridadService {
        
        public SeguridadServiceClient() {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPC.SisTictecks.EL.UsuarioEN AutenticarUsuario(string usuario, string pass) {
            return base.Channel.AutenticarUsuario(usuario, pass);
        }
        
        public System.Threading.Tasks.Task<UPC.SisTictecks.EL.UsuarioEN> AutenticarUsuarioAsync(string usuario, string pass) {
            return base.Channel.AutenticarUsuarioAsync(usuario, pass);
        }
    }
}
